version: "3.9"
services:

  api01: &api
    build: 
      context: ../app
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: api01
    hostname: api01
    restart: on-failure
    environment:
      - DB_HOST=postgres-db
      - PROFILE=local
      - PORT=20000
      - JVM_XMS=140m
      - JVM_XMX=220m
      - CONTAINER_MEMORY=220m
      - NEW_SIZE=5m
      - MAX_NEW_SIZE=8m
      - MIN_HEAP_FREE_RATIO=20
      - MAX_HEAP_FREE_RATIO=70
      - MIN_POOL_CONNECTION=3
      - MAX_POOL_CONNECTION=3
    depends_on:
      - postgres-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "232MB"

  api02:
    <<: *api 
    hostname: api02
    container_name: api02
    environment:
      - DB_HOST=postgres-db
      - PORT=20000
      - PROFILE=local
      - JVM_XMS=140m
      - JVM_XMX=220m
      - NEW_SIZE=5m
      - MAX_NEW_SIZE=8m
      - CONTAINER_MEMORY=220m
      - MIN_HEAP_FREE_RATIO=20
      - MAX_HEAP_FREE_RATIO=70
      - MIN_POOL_CONNECTION=3
      - MAX_POOL_CONNECTION=3

  nginx:
    image: nginx:latest
    restart: on-failure
    container_name: loadbalancer
    depends_on:
      - api01
      - api02
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "12MB"
    networks:
      - default
        
  postgres-db:
    image:  postgres:15.3-bullseye
    container_name: postgres-db
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '74MB'
    ports:
      - "5433:5432"
    volumes:
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf:z
      - ./data/init-sql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "rinha"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
      - PGUSER=postgres
    networks:
      - default


networks:
  default:
    driver: bridge