spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5433}/rinha
    username: ${BD_USERNAME:postgres}
    password: ${BD_PASSWORD:postgres}
    max-active: ${MAX_POOL_CONNECTION:4}
    min-active: ${MIN_POOL_CONNECTION:4}
    hikari:
      maximum-pool-size: ${MAX_POOL_CONNECTION:4}
      minimum-pool-size: ${MIN_POOL_CONNECTION:4}
    tomcat:
      max-active: ${MAX_THREAD:5}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: OFF
  root: OFF

server:
  port: ${PORT:20000}
  tomcat:
    max-threads: ${MAX_THREAD:4}
    max-connections: ${MAX_THREAD:4}